# These are the funding platforms supported by GitHub Sponsors.
# You can specify multiple funding options if you use different platforms.

github: your-username
patreon: your-patreon-id
open_collective: your-open-collective-id
ko_fi: your-kofi-id
tidelift: your-tidelift-id
custom: https://your-custom-funding-page.com
